name: Rust

on:
  push:
    branches:
      - main
    tags:
      - "*"

env:
  RUST_BACKTRACE: 1

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Run cargo check
        run: cargo check
  
  lints:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain with necessary components
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        # This step checks if the code follows Rust's formatting conventions

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
        # This step checks for common code quality issues

  audit:
    name: Audit Code
    runs-on: ubuntu-latest
    needs: lints

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Audit code
        run: cargo audit
        # This step checks for known security vulnerabilities in the project's dependencies

  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust:
          - { version: "1.69", name: msrv }
          - { version: stable, name: stable }

    runs-on: ${{ matrix.os }}
    name: Tests (${{ matrix.os }}, ${{ matrix.rust.name }})
    needs: audit
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install ${{ matrix.rust.name }} toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust.version }}

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Unit Test (debug)
        run: cargo test --verbose

  # # Under construction
  # fuzzing:
  #   name: Fuzz Code
  #   runs-on: ubuntu-latest
  #   needs: tests

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install Rust
  #     uses: actions-rs/toolchain@v1
  #     with:
  #       toolchain: nightly
  #       override: true
  #   - name: Install cargo-fuzz
  #     run: cargo install cargo-fuzz
  #   - name: Run Fuzzing
  #     run: cargo fuzz run calculate -- -max_total_time=180

  docs:
    name: Generate Docs
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Generate documentation
        run: cargo doc --no-deps
        # This step generates the project documentation without including dependencies

      - name: Publish documentation
        uses: actions/upload-artifact@v2
        with:
          name: Documentation
          path: target/doc/
        # This step uploads the generated documentation as an artifact